spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        
  application:
    name: Api-Gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCB
                fallbackUri: forward:/fallback/product
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/category/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCB
                fallbackUri: forward:/fallback/product

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartServiceCB
                fallbackUri: forward:/fallback/cart
                
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCB
                fallbackUri: forward:/fallback/orders
                
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryServiceCB
                fallbackUri: forward:/fallback/inventory
                
         

resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        register-health-indicator: true
      productServiceCB:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        register-health-indicator: true
      cartServiceCB:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        register-health-indicator: true
      orderServiceCB:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        register-health-indicator: true
      inventoryServiceCB:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        register-health-indicator: true
         
          

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8089
  
management:
  tracing:
    sampling:
      probability: 1.0
      
      
  endpoints:
    web:
      exposure:
        include: '*'
        
        


logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[io.github.resilience4j]': DEBUG






























